server:
  port: 8080 # 避免和本地的 Apollo Portal 端口冲突

app:
  id: demo-application # 使用的 Apollo 的项目（应用）编号
apollo:
  meta: http://139.196.173.8:8080 # Apollo Meta Server 地址
  bootstrap:
    enabled: true # 是否开启 Apollo 配置预加载功能。默认为 false。
    eagerLoad:
      enable: true # 是否开启 Apollo 支持日志级别的加载时机。默认为 false。
    namespaces: application # 使用的 Apollo 的命名空间，默认为 application。
  cacheDir: ./apollo-config # Apollo 配置缓存目录
  cluster: default # Apollo 集群名称，默认为 default
  autoUpdateInjectedSpringProperties: true # 自动更新注入的Spring属性
  refreshInterval: 1000 # 配置刷新间隔，单位毫秒
  configServiceUrl: http://139.196.173.8:8080 # Apollo Config Service 地址
  property:
    order:
      enabled: true # 是否开启配置项排序功能
  configService:
    refreshInterval: 1000 # 配置服务刷新间隔，单位毫秒

end:

